using Newtonsoft.Json;
using System;
// <auto-generated />
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//    using Contributors;
//    var welcome = Welcome.FromJson(jsonString);

namespace RepoStrategy.Model
{
    public class TeamResult : IComparable<TeamResult>
    {

        [JsonProperty("alternate_name", NullValueHandling = NullValueHandling.Ignore)]
        public object AlternateName { get; set; }

        [JsonProperty("country",NullValueHandling = NullValueHandling.Ignore)]
        public string Country { get; set; }

        [JsonProperty("draws",NullValueHandling = NullValueHandling.Ignore)]
        public long Draws { get; set; }

        [JsonProperty("fifa_code", NullValueHandling = NullValueHandling.Ignore)]
        public string FifaCode { get; set; }

        [JsonProperty("games_played", NullValueHandling = NullValueHandling.Ignore)]
        public long GamesPlayed { get; set; }

        [JsonProperty("goal_differential", NullValueHandling = NullValueHandling.Ignore)]
        public long GoalDifferential { get; set; }

        [JsonProperty("goals_against", NullValueHandling = NullValueHandling.Ignore)]
        public long GoalsAgainst { get; set; }

        [JsonProperty("goals_for", NullValueHandling = NullValueHandling.Ignore)]
        public long GoalsFor { get; set; }

        [JsonProperty("group_id", NullValueHandling = NullValueHandling.Ignore)]
        public long GroupId { get; set; }

        [JsonProperty("group_letter", NullValueHandling = NullValueHandling.Ignore)]
        public string GroupLetter { get; set; }
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long Id { get; set; }

        [JsonProperty("losses", NullValueHandling = NullValueHandling.Ignore)]
        public long Losses { get; set; }

        [JsonProperty("points", NullValueHandling = NullValueHandling.Ignore)]
        public long Points { get; set; }

        [JsonProperty("wins", NullValueHandling = NullValueHandling.Ignore)]
        public long Wins { get; set; }

        public int CompareTo(TeamResult other) => Country.CompareTo(other.Country);
        public override bool Equals(object obj) =>  obj is TeamResult result && Id == result.Id;
        public override int GetHashCode() => 2108858624 + Id.GetHashCode();
        


        //public override string ToString()
        //{
        //    return $"ID: {Id},  " +
        //        $"Country: {Country}, " +
        //        $"AlternateName: {AlternateName}, " +
        //        $"FifaCode: {FifaCode}, " +
        //        $"GroupId: {GroupId}, " +
        //        $"GroupLetter: {GroupLetter}, " +
        //        $"Wins: {Wins}, " +
        //        $"Draws: {Draws}, " +
        //        $"Loses: {Losses}, " +
        //        $"Games played: {GamesPlayed}, " +
        //        $"Points: {Points}," +
        //        $"GoalsFor: {GoalsFor}," +
        //        $"GoalsAgainst: {GoalsAgainst}," +
        //        $"GoalDiff:  {GoalDifferential}";
        //}

    }
}