//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManagerFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class hrv_RankingsLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hrv_RankingsLocal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballManagerFormsApp.hrv_RankingsLocal", typeof(hrv_RankingsLocal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printaj rangiranja.
        /// </summary>
        internal static string btnPrintRankings {
            get {
                return ResourceManager.GetString("btnPrintRankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posloži po.
        /// </summary>
        internal static string cbOrderRankingBy {
            get {
                return ResourceManager.GetString("cbOrderRankingBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolaznost.
        /// </summary>
        internal static string chAttendence {
            get {
                return ResourceManager.GetString("chAttendence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gosti.
        /// </summary>
        internal static string chAwayTeam {
            get {
                return ResourceManager.GetString("chAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domacin.
        /// </summary>
        internal static string chHomeTeam {
            get {
                return ResourceManager.GetString("chHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string chLocation {
            get {
                return ResourceManager.GetString("chLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangiranje po dolaznosti.
        /// </summary>
        internal static string lbAttendenceRanking {
            get {
                return ResourceManager.GetString("lbAttendenceRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangiranje igrača.
        /// </summary>
        internal static string lbPlayerRankings {
            get {
                return ResourceManager.GetString("lbPlayerRankings", resourceCulture);
            }
        }
    }
}
